In [10]:
import pandas as pd 

total_dataset_v3 = pd.read_csv('./total_cleaned_v2.csv', sep=',')

print(total_dataset_v3)

     Unnamed: 0  Respondentnummer  Gender Zip-code Geboortedatum  \
0             0          210153.0     1.0  2516 VN    21.08.2016
1             1          212120.0     1.0  3079 HK    12.01.2016
2             2          219179.0     1.0  2526 HR    19.01.2016
3             3          219172.0     0.0  2526 HR    17.01.2016
4             4          201163.0     0.0      NaN    17.12.2015
..          ...               ...     ...      ...           ...
547         547          219304.0     1.0      NaN    30.01.2013
548         548          207117.0     1.0  2313 AB    07.05.2013
549         549          209121.0     0.0  2571 VD    10.07.2013
550         550          209146.0     0.0  2571 VD    07.02.2013
551         551          202175.0     1.0  3082 VW    28.03.2014

     Age on testday (t0)  Leeftijd (op testdag)  AST (tijd afgerond op 0.1s)  \
0                 4.0903                 4.0903                     28.10000
1                 4.1424                 4.1424                     45.60000
2                 4.1424                 4.1424                     40.40000
3                 4.1478                 4.1478                     35.60000
4                 4.1780                 4.1780                     38.70000
..                   ...                    ...                          ...
547               7.1102                 7.1102                     30.40000
548               7.1704                 7.1704                     22.80000
549               7.2197                 7.2197                     17.56000
550               7.6386                 7.6386                     17.43000
551                  NaN                19.7000                    109.64467

             MQ  Lengte (afgerond op 0.1 cm)  ...  4. Bal vangen 2  \
0    112.811388                        103.1  ...                1
1     69.517544                        105.0  ...                4
2     78.465347                        102.0  ...              NaN
3     88.061798                        109.0  ...              NaN
4     81.007752                        108.0  ...                4
..          ...                          ...  ...              ...
547         NaN                        117.0  ...              NaN
548    0.000000                        114.2  ...                4
549         NaN                        119.0  ...              NaN
550         NaN                        120.3  ...                4
551  112.000000                         17.9  ...                1

     5. Hinkelen 2  6. Bal rollen 2  7. Loopsprong 2  8. Bal schoppen 2  \
0                2                4                1                  3
1                4                4                4                  4
2              NaN              NaN              NaN                NaN
3              NaN              NaN              NaN                NaN
4                4                4                4                  4
..             ...              ...              ...                ...
547            NaN              NaN              NaN                NaN
548              4                4                4                  2
549            NaN              NaN              NaN                NaN
550              3                4                4                  3
551              4                4                4                  4

     9. Voorw. Springen 2  10. Knuppel 2  11. Zijw. Gallop 2  \
0                       1              1                   1
1                       4              4                   4
2                     NaN            NaN                 NaN
3                     NaN            NaN                 NaN
4                       4              4                   4
..                    ...            ...                 ...
547                   NaN            NaN                 NaN
548                     4              4                   4
549                   NaN            NaN                 NaN
550                     4              3                   3
551                     4              2                   4

     12. Stuiten bal 2  Testdatum 2
0                    1   07.04.2021
1                    4   29.03.2021
2                  NaN   17.06.2021
3                  NaN   17.06.2021
4                    4   31.03.2021
..                 ...          ...
547                NaN          NaN
548                  4   12.04.2021
549                NaN   17.05.2021
550                  4   17.05.2021
551                  4   21.06.2021

[552 rows x 181 columns]

In [11]:
print(total_dataset_v3)

     Unnamed: 0  Respondentnummer  Gender Zip-code Geboortedatum  \
0             0          210153.0     1.0  2516 VN    21.08.2016
1             1          212120.0     1.0  3079 HK    12.01.2016
2             2          219179.0     1.0  2526 HR    19.01.2016
3             3          219172.0     0.0  2526 HR    17.01.2016
4             4          201163.0     0.0      NaN    17.12.2015
..          ...               ...     ...      ...           ...
547         547          219304.0     1.0      NaN    30.01.2013
548         548          207117.0     1.0  2313 AB    07.05.2013
549         549          209121.0     0.0  2571 VD    10.07.2013
550         550          209146.0     0.0  2571 VD    07.02.2013
551         551          202175.0     1.0  3082 VW    28.03.2014

     Age on testday (t0)  Leeftijd (op testdag)  AST (tijd afgerond op 0.1s)  \
0                 4.0903                 4.0903                     28.10000
1                 4.1424                 4.1424                     45.60000
2                 4.1424                 4.1424                     40.40000
3                 4.1478                 4.1478                     35.60000
4                 4.1780                 4.1780                     38.70000
..                   ...                    ...                          ...
547               7.1102                 7.1102                     30.40000
548               7.1704                 7.1704                     22.80000
549               7.2197                 7.2197                     17.56000
550               7.6386                 7.6386                     17.43000
551                  NaN                19.7000                    109.64467

             MQ  Lengte (afgerond op 0.1 cm)  ...  4. Bal vangen 2  \
0    112.811388                        103.1  ...                1
1     69.517544                        105.0  ...                4
2     78.465347                        102.0  ...              NaN
3     88.061798                        109.0  ...              NaN
4     81.007752                        108.0  ...                4
..          ...                          ...  ...              ...
547         NaN                        117.0  ...              NaN
548    0.000000                        114.2  ...                4
549         NaN                        119.0  ...              NaN
550         NaN                        120.3  ...                4
551  112.000000                         17.9  ...                1

     5. Hinkelen 2  6. Bal rollen 2  7. Loopsprong 2  8. Bal schoppen 2  \
0                2                4                1                  3
1                4                4                4                  4
2              NaN              NaN              NaN                NaN
3              NaN              NaN              NaN                NaN
4                4                4                4                  4
..             ...              ...              ...                ...
547            NaN              NaN              NaN                NaN
548              4                4                4                  2
549            NaN              NaN              NaN                NaN
550              3                4                4                  3
551              4                4                4                  4

     9. Voorw. Springen 2  10. Knuppel 2  11. Zijw. Gallop 2  \
0                       1              1                   1
1                       4              4                   4
2                     NaN            NaN                 NaN
3                     NaN            NaN                 NaN
4                       4              4                   4
..                    ...            ...                 ...
547                   NaN            NaN                 NaN
548                     4              4                   4
549                   NaN            NaN                 NaN
550                     4              3                   3
551                     4              2                   4

     12. Stuiten bal 2  Testdatum 2
0                    1   07.04.2021
1                    4   29.03.2021
2                  NaN   17.06.2021
3                  NaN   17.06.2021
4                    4   31.03.2021
..                 ...          ...
547                NaN          NaN
548                  4   12.04.2021
549                NaN   17.05.2021
550                  4   17.05.2021
551                  4   21.06.2021

[552 rows x 181 columns]

In [12]:
total_dataset_v3.drop('Unnamed: 0', axis=1, inplace=True)

In [13]:
print(total_dataset_v3)

     Respondentnummer  Gender Zip-code Geboortedatum  Age on testday (t0)  \
0            210153.0     1.0  2516 VN    21.08.2016               4.0903
1            212120.0     1.0  3079 HK    12.01.2016               4.1424
2            219179.0     1.0  2526 HR    19.01.2016               4.1424
3            219172.0     0.0  2526 HR    17.01.2016               4.1478
4            201163.0     0.0      NaN    17.12.2015               4.1780
..                ...     ...      ...           ...                  ...
547          219304.0     1.0      NaN    30.01.2013               7.1102
548          207117.0     1.0  2313 AB    07.05.2013               7.1704
549          209121.0     0.0  2571 VD    10.07.2013               7.2197
550          209146.0     0.0  2571 VD    07.02.2013               7.6386
551          202175.0     1.0  3082 VW    28.03.2014                  NaN

     Leeftijd (op testdag)  AST (tijd afgerond op 0.1s)          MQ  \
0                   4.0903                     28.10000  112.811388
1                   4.1424                     45.60000   69.517544
2                   4.1424                     40.40000   78.465347
3                   4.1478                     35.60000   88.061798
4                   4.1780                     38.70000   81.007752
..                     ...                          ...         ...
547                 7.1102                     30.40000         NaN
548                 7.1704                     22.80000    0.000000
549                 7.2197                     17.56000         NaN
550                 7.6386                     17.43000         NaN
551                19.7000                    109.64467  112.000000

     Lengte (afgerond op 0.1 cm)  Gewicht (afgerond op 0.1 kg)  ...  \
0                          103.1                         17.20  ...
1                          105.0                         17.00  ...
2                          102.0                         15.20  ...
3                          109.0                         19.20  ...
4                          108.0                         18.50  ...
..                           ...                           ...  ...
547                        117.0                         20.70  ...
548                        114.2                         22.40  ...
549                        119.0                         21.40  ...
550                        120.3                         24.80  ...
551                         17.9                          1.12  ...

     4. Bal vangen 2  5. Hinkelen 2  6. Bal rollen 2  7. Loopsprong 2  \
0                  1              2                4                1
1                  4              4                4                4
2                NaN            NaN              NaN              NaN
3                NaN            NaN              NaN              NaN
4                  4              4                4                4
..               ...            ...              ...              ...
547              NaN            NaN              NaN              NaN
548                4              4                4                4
549              NaN            NaN              NaN              NaN
550                4              3                4                4
551                1              4                4                4

     8. Bal schoppen 2  9. Voorw. Springen 2  10. Knuppel 2  \
0                    3                     1              1
1                    4                     4              4
2                  NaN                   NaN            NaN
3                  NaN                   NaN            NaN
4                    4                     4              4
..                 ...                   ...            ...
547                NaN                   NaN            NaN
548                  2                     4              4
549                NaN                   NaN            NaN
550                  3                     4              3
551                  4                     4              2

     11. Zijw. Gallop 2  12. Stuiten bal 2  Testdatum 2
0                     1                  1   07.04.2021
1                     4                  4   29.03.2021
2                   NaN                NaN   17.06.2021
3                   NaN                NaN   17.06.2021
4                     4                  4   31.03.2021
..                  ...                ...          ...
547                 NaN                NaN          NaN
548                   4                  4   12.04.2021
549                 NaN                NaN   17.05.2021
550                   3                  4   17.05.2021
551                   4                  4   21.06.2021

[552 rows x 180 columns]

In [15]:
total_dataset_v3.drop('Leeftijd (op testdag)', axis=1, inplace=True)

In [16]:
print(total_dataset_v3)

     Respondentnummer  Gender Zip-code Geboortedatum  Age on testday (t0)  \
0            210153.0     1.0  2516 VN    21.08.2016               4.0903
1            212120.0     1.0  3079 HK    12.01.2016               4.1424
2            219179.0     1.0  2526 HR    19.01.2016               4.1424
3            219172.0     0.0  2526 HR    17.01.2016               4.1478
4            201163.0     0.0      NaN    17.12.2015               4.1780
..                ...     ...      ...           ...                  ...
547          219304.0     1.0      NaN    30.01.2013               7.1102
548          207117.0     1.0  2313 AB    07.05.2013               7.1704
549          209121.0     0.0  2571 VD    10.07.2013               7.2197
550          209146.0     0.0  2571 VD    07.02.2013               7.6386
551          202175.0     1.0  3082 VW    28.03.2014                  NaN

     AST (tijd afgerond op 0.1s)          MQ  Lengte (afgerond op 0.1 cm)  \
0                       28.10000  112.811388                        103.1
1                       45.60000   69.517544                        105.0
2                       40.40000   78.465347                        102.0
3                       35.60000   88.061798                        109.0
4                       38.70000   81.007752                        108.0
..                           ...         ...                          ...
547                     30.40000         NaN                        117.0
548                     22.80000    0.000000                        114.2
549                     17.56000         NaN                        119.0
550                     17.43000         NaN                        120.3
551                    109.64467  112.000000                         17.9

     Gewicht (afgerond op 0.1 kg)  Lengte (in m)  ...  4. Bal vangen 2  \
0                           17.20           1.03  ...                1
1                           17.00           1.05  ...                4
2                           15.20           1.02  ...              NaN
3                           19.20           1.09  ...              NaN
4                           18.50           1.08  ...                4
..                            ...            ...  ...              ...
547                         20.70           1.17  ...              NaN
548                         22.40           1.14  ...                4
549                         21.40           1.19  ...              NaN
550                         24.80           1.20  ...                4
551                          1.12          14.27  ...                1

     5. Hinkelen 2  6. Bal rollen 2  7. Loopsprong 2  8. Bal schoppen 2  \
0                2                4                1                  3
1                4                4                4                  4
2              NaN              NaN              NaN                NaN
3              NaN              NaN              NaN                NaN
4                4                4                4                  4
..             ...              ...              ...                ...
547            NaN              NaN              NaN                NaN
548              4                4                4                  2
549            NaN              NaN              NaN                NaN
550              3                4                4                  3
551              4                4                4                  4

     9. Voorw. Springen 2  10. Knuppel 2  11. Zijw. Gallop 2  \
0                       1              1                   1
1                       4              4                   4
2                     NaN            NaN                 NaN
3                     NaN            NaN                 NaN
4                       4              4                   4
..                    ...            ...                 ...
547                   NaN            NaN                 NaN
548                     4              4                   4
549                   NaN            NaN                 NaN
550                     4              3                   3
551                     4              2                   4

     12. Stuiten bal 2  Testdatum 2
0                    1   07.04.2021
1                    4   29.03.2021
2                  NaN   17.06.2021
3                  NaN   17.06.2021
4                    4   31.03.2021
..                 ...          ...
547                NaN          NaN
548                  4   12.04.2021
549                NaN   17.05.2021
550                  4   17.05.2021
551                  4   21.06.2021

[552 rows x 179 columns]

In [17]:
total_dataset_v3.to_csv(r'./total_cleaned_v3.csv')